# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Бесплатная пробная версия (e4384d65-2fd1-4efa-be81-1b4feb246bd6)'
    appType: 'webApp'
    WebAppName: 'Intravision'
    deployToSlotOrASE: true
    ResourceGroupName: 'IntravisionGroup'
    SlotName: 'staging'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

